module.exports = {
  PULSE_DURATION_MS: 1000,
  DEFAULT_POLL_TIMEOUT_MS: 2000,
  DEFAULT_UPDATE_INTERVAL_MS: 5000,
  MAX_BACKOFF_MS: 40000,
  MIN_ETA_FOR_HOURS: 3600,
  MIN_SPEED_FOR_MB: 1048576,
  INFINITE_ETA: 8640000,
  AUTH_RETRY_DELAY_MS: 100,
  ACTION_BATCH_DELAY_MS: 100,
  IDLE_POLL_MULTIPLIER: 4,
  API_AUTH_LOGIN: "/api/v2/auth/login",
  API_APP_VERSION: "/api/v2/app/version",
  API_TORRENTS_INFO: "/api/v2/torrents/info",
  API_TORRENTS_RESUME: "/api/v2/torrents/resume",
  API_TORRENTS_PAUSE: "/api/v2/torrents/pause",
  API_TORRENTS_START: "/api/v2/torrents/start",
  API_TORRENTS_STOP: "/api/v2/torrents/stop",
  API_TRANSFER_INFO: "/api/v2/transfer/info"
};
